services:
  mongodb:
    image: mongo:8
    container_name: automail-autocaller-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: automail_autocaller
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: automail-autocaller-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:
