import { z } from 'zod';

/**
 * Gmail App Passwords are 16 lowercase letters, commonly shown in four groups
 * of four. Spaces are stripped before validation so a pasted value works.
 */
const appPasswordSchema = z
  .string()
  .min(1, 'Enter the App Password generated by Google')
  .transform((value) => value.replace(/\s+/g, ''))
  .refine((value) => value.length === 16, {
    message: 'A Gmail App Password is 16 characters long',
  })
  .refine((value) => /^[a-zA-Z]+$/.test(value), {
    message: 'A Gmail App Password contains only letters',
  });

export const connectAccountSchema = z.object({
  email: z
    .string()
    .trim()
    .toLowerCase()
    .email('Enter a valid email address')
    .max(320)
    .refine(
      (value) =>
        value.endsWith('@gmail.com') ||
        value.endsWith('@googlemail.com') ||
        !value.endsWith('@yahoo.com'),
      { message: 'Connect a Gmail or Google Workspace address' },
    ),
  displayName: z.string().trim().min(1, 'Enter a sender name').max(120),
  appPassword: appPasswordSchema,
  makeDefault: z.boolean().default(false),
});

export const sendTestEmailSchema = z.object({
  to: z.string().trim().toLowerCase().email('Enter a valid email address').max(320).optional(),
});

export type ConnectAccountBody = z.infer<typeof connectAccountSchema>;
export type SendTestEmailBody = z.infer<typeof sendTestEmailSchema>;
